### Ejemplo de los Mensajes para el juego del *Ciclo* de Myerson

Se tata de la situación de comnicación de Myerson representada por el ciclo abajo dibujado. La matriz de adyacencia de este grafo es la siguiente:

$$ \begin{bmatrix}
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 \\
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0
\end{bmatrix} $$

In [ ]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import shap

adjacency = pd.DataFrame([
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
])
index = [
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
]
adjacency.columns = index
adjacency["index"] = index
adjacency = adjacency.set_index("index", verify_integrity=True)

g = nx.from_pandas_adjacency(adjacency)
pos = nx.kamada_kawai_layout(g)
nx.draw(
    g, pos, with_labels=True,
    node_color="red", font_color="white",
    font_weight="bold", node_size=400
)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import os
import sys
import math
import pandas as pd


file_root_shapley = os.path.join(
    "..", "..", "data", "exact", "shapley_value_of_myerson_coalitions_cycle.csv"
)
file_root_grabisch = os.path.join(
    "..", "..", "data", "exact", "shapley_diff_value_of_myerson_coalitions_cycle.csv"
)

index = [
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
]
shapley_only = pd.read_csv(
    file_root_shapley,
    sep=";",
    header=None,
    names=["value"]
)
shapley_only["player"] = index
psi_1 = shapley_only.set_index("player", verify_integrity=True)

r_1 = pd.read_csv(
    file_root_grabisch,
    sep=";",
    header=0
)
r_1.columns = index
r_1["player"] = index
r_1 = r_1.set_index("player", verify_integrity=True)

### Truncated characteristic values

In [ ]:
from cgt_perezsechi.manipulation.norm import normalize_psi, normalize_r


n = 4
psi_1_truncated = psi_1.copy()
psi_1_truncated["value"] = psi_1_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_1_truncated = r_1.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

psi_2 = normalize_psi(psi_1)
psi_2_truncated = psi_2.copy()
psi_2_truncated["value"] = psi_2_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_2 = normalize_r(r_1)
r_2_truncated = r_2.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

#### Cost Allocation Results

The Shapley values for this game are calculated in the file ./data/exact/shapley_value_of_myerson_coalitions_chain.csv. In the table below we represent these values:

In [ ]:
psi_1_truncated

        value
player
P1        4.5
P2        4.5
P3        4.5
P4        4.5
P5        4.5
P6        4.5
P7        4.5
P8        4.5
P9        4.5
P10       4.5

In [ ]:
psi_2_truncated

        value
player
P1        1.0
P2        1.0
P3        1.0
P4        1.0
P5        1.0
P6        1.0
P7        1.0
P8        1.0
P9        1.0
P10       1.0

The Grabisch values of all the pairs in the game can be found in the file ./data/exact/grabisch_of_myerson_coalitions_chain.csv. In the following table, we represent these values.

In [ ]:
r_1_truncated

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10
player,,,,,,,,,,
P1,0.0000,2.6710,0.9531,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397,0.9531,2.6710
P2,2.6710,0.0000,2.6710,0.9531,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397,0.9531
P3,0.9531,2.6710,0.0000,2.6710,0.9531,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397
P4,-0.1397,0.9531,2.6710,0.0000,2.6710,0.9531,-0.1397,-0.7564,-0.9564,-0.7564
P5,-0.7564,-0.1397,0.9531,2.6710,0.0000,2.6710,0.9531,-0.1397,-0.7564,-0.9564
P6,-0.9564,-0.7564,-0.1397,0.9531,2.6710,0.0000,2.6710,0.9531,-0.1397,-0.7564
P7,-0.7564,-0.9564,-0.7564,-0.1397,0.9531,2.6710,0.0000,2.6710,0.9531,-0.1397
P8,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397,0.9531,2.6710,0.0000,2.6710,0.9531
P9,0.9531,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397,0.9531,2.6710,0.0000,2.6710
P10,2.6710,0.9531,-0.1397,-0.7564,-0.9564,-0.7564,-0.1397,0.9531,2.6710,0.0000

In [ ]:
r_2_truncated

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10
player,,,,,,,,,,
P1,0.0000,1.0000,0.3568,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523,0.3568,1.0000
P2,1.0000,0.0000,1.0000,0.3568,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523,0.3568
P3,0.3568,1.0000,0.0000,1.0000,0.3568,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523
P4,-0.0523,0.3568,1.0000,0.0000,1.0000,0.3568,-0.0523,-0.2832,-0.3581,-0.2832
P5,-0.2832,-0.0523,0.3568,1.0000,0.0000,1.0000,0.3568,-0.0523,-0.2832,-0.3581
P6,-0.3581,-0.2832,-0.0523,0.3568,1.0000,0.0000,1.0000,0.3568,-0.0523,-0.2832
P7,-0.2832,-0.3581,-0.2832,-0.0523,0.3568,1.0000,0.0000,1.0000,0.3568,-0.0523
P8,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523,0.3568,1.0000,0.0000,1.0000,0.3568
P9,0.3568,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523,0.3568,1.0000,0.0000,1.0000
P10,1.0000,0.3568,-0.0523,-0.2832,-0.3581,-0.2832,-0.0523,0.3568,1.0000,0.0000

### Absolute value $\|I\|$

In [ ]:
r_1_abs = r_1.astype(float).apply(lambda row: row.apply(lambda number: abs(number)))
r_1_abs

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10
player,,,,,,,,,,
P1,0.000000,2.671032,0.953175,0.139683,0.756349,0.956349,0.756349,0.139683,0.953175,2.671032
P2,2.671032,0.000000,2.671032,0.953175,0.139683,0.756349,0.956349,0.756349,0.139683,0.953175
P3,0.953175,2.671032,0.000000,2.671032,0.953175,0.139683,0.756349,0.956349,0.756349,0.139683
P4,0.139683,0.953175,2.671032,0.000000,2.671032,0.953175,0.139683,0.756349,0.956349,0.756349
P5,0.756349,0.139683,0.953175,2.671032,0.000000,2.671032,0.953175,0.139683,0.756349,0.956349
P6,0.956349,0.756349,0.139683,0.953175,2.671032,0.000000,2.671032,0.953175,0.139683,0.756349
P7,0.756349,0.956349,0.756349,0.139683,0.953175,2.671032,0.000000,2.671032,0.953175,0.139683
P8,0.139683,0.756349,0.956349,0.756349,0.139683,0.953175,2.671032,0.000000,2.671032,0.953175
P9,0.953175,0.139683,0.756349,0.956349,0.756349,0.139683,0.953175,2.671032,0.000000,2.671032
P10,2.671032,0.953175,0.139683,0.756349,0.956349,0.756349,0.139683,0.953175,2.671032,0.000000

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 0}^{2}; R_{\beta^{+} = 0, \beta^{-} = 1}^{2}$

In [ ]:
import os
import sys

from cgt_perezsechi.visualization.graph import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=0,
    positive_beta=0,
    negative_beta=1,
    symmetric=True,
    layout="circular",
    output_path=os.path.join("..", "..", "results", "myerson-cycle-messages-0-0-0-1.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\myerson-cycle-messages-0-0-0-1.jpg

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 0}^{2}; R_{\beta^{+} = 1, \beta^{-} = 0}^{2}$

In [ ]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=0,
    positive_beta=1,
    negative_beta=0,
    symmetric=True,
    layout="circular",
    output_path=os.path.join("..", "..", "results", "myerson-cycle-messages-0-0-1-0.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\myerson-cycle-messages-0-0-1-0.jpg