### Ejemplo de coaliación en el juego de votaciones

In [1]:
import os
import sys
import math
import pandas as pd


sys.path.append(os.path.join("..", "..", "."))

file_root_shapley = os.path.join(
    "..", "..", "data", "exact", "shapley_value_of_parliament.csv"
)
file_root_grabisch = os.path.join(
    "..", "..", "data", "exact", "grabisch_of_parliament.csv"
)
original = pd.read_csv(os.path.join(
    "..", "..", "data", "input", "parliament.csv"
), sep=";").set_index(
    "label",
    verify_integrity=True
)

shapley_only = pd.read_csv(
    file_root_shapley,
    sep=";",
    header=None,
    names=["value"]
)
shapley_only = shapley_only.set_index(
    original.index.values,
    verify_integrity=True
)
psi_1 = original.join(shapley_only)

r_1 = pd.read_csv(
    file_root_grabisch,
    sep=";",
    header=0
).set_index(
    original.index.values,
    verify_integrity=True
)
r_1.columns = original.index.values

In [2]:
display(r_1)

,A,B,C,D,E,F,G,H,I,J
A,0.000000,0.014286,-0.004762,-0.002381,0.004762,-0.002381,-0.002381,-0.007143,0.000000,0.000000
B,0.014286,0.000000,-0.002381,0.000000,-0.009524,0.000000,0.000000,-0.002381,0.000000,0.000000
C,-0.004762,-0.002381,0.000000,0.014286,0.004762,-0.002381,-0.002381,-0.007143,0.000000,0.000000
D,-0.002381,0.000000,0.014286,0.000000,-0.009524,0.000000,0.000000,-0.002381,0.000000,0.000000
E,0.004762,-0.009524,0.004762,-0.009524,0.000000,0.007143,0.007143,-0.004762,0.000000,0.000000
F,-0.002381,0.000000,-0.002381,0.000000,0.007143,0.000000,0.000000,-0.002381,0.000000,0.000000
G,-0.002381,0.000000,-0.002381,0.000000,0.007143,0.000000,0.000000,-0.002381,0.000000,0.000000
H,-0.007143,-0.002381,-0.007143,-0.002381,-0.004762,-0.002381,-0.002381,0.000000,0.014286,0.014286
I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014286,0.000000,-0.014286
J,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014286,-0.014286,0.000000

### Truncated characteristic values

In [3]:
from graph.manipulation import normalize_psi, normalize_r


n = 4
psi_1_truncated = psi_1.copy()
psi_1_truncated["value"] = psi_1_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_1_truncated = r_1.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

psi_2 = normalize_psi(psi_1)
psi_2_truncated = psi_2.copy()
psi_2_truncated["value"] = psi_2_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_2 = normalize_r(r_1)
r_2_truncated = r_2.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

#### Benefit Allocation Results

The Shapley values for this game are calculated in the file ./data/exact/shapley_value_of_bankruptcy.csv. In the table below we represent these values:

In [4]:
psi_1_truncated

                           player  votes   value
label
A                    Labour Party     29  0.3226
B              Conservative Party     26  0.2615
C                    Centre Party     16  0.1559
D                  Progress Party     13  0.0948
E            Socialist Left Party      6  0.0753
F                   Liberal Party      3  0.0281
G                       Red Party      3  0.0281
H                     Green Party      2  0.0206
I      Christian Democratic Party      1  0.0063
J                   Patient Focus      1  0.0063

In [5]:
psi_2_truncated

                           player  votes   value
label
A                    Labour Party     29  1.0000
B              Conservative Party     26  0.8105
C                    Centre Party     16  0.4833
D                  Progress Party     13  0.2939
E            Socialist Left Party      6  0.2337
F                   Liberal Party      3  0.0873
G                       Red Party      3  0.0873
H                     Green Party      2  0.0639
I      Christian Democratic Party      1  0.0196
J                   Patient Focus      1  0.0196

The Grabisch values of all the pairs in the game can be found in the file ./data/exact/grabisch_of_bankruptcy.csv. In the following table, we represent these values.

In [6]:
r_1_truncated

,A,B,C,D,E,F,G,H,I,J
A,0.0000,0.0142,-0.0048,-0.0024,0.0047,-0.0024,-0.0024,-0.0072,0.0000,0.0000
B,0.0142,0.0000,-0.0024,0.0000,-0.0096,0.0000,0.0000,-0.0024,0.0000,0.0000
C,-0.0048,-0.0024,0.0000,0.0142,0.0047,-0.0024,-0.0024,-0.0072,0.0000,0.0000
D,-0.0024,0.0000,0.0142,0.0000,-0.0096,0.0000,0.0000,-0.0024,0.0000,0.0000
E,0.0047,-0.0096,0.0047,-0.0096,0.0000,0.0071,0.0071,-0.0048,0.0000,0.0000
F,-0.0024,0.0000,-0.0024,0.0000,0.0071,0.0000,0.0000,-0.0024,0.0000,0.0000
G,-0.0024,0.0000,-0.0024,0.0000,0.0071,0.0000,0.0000,-0.0024,0.0000,0.0000
H,-0.0072,-0.0024,-0.0072,-0.0024,-0.0048,-0.0024,-0.0024,0.0000,0.0142,0.0142
I,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0142,0.0000,-0.0143
J,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0142,-0.0143,0.0000

In [7]:
r_2_truncated

        A       B       C       D       E       F       G       H    I    J
A  0.0000  1.0000 -0.3334 -0.1667  0.3333 -0.1667 -0.1667 -0.5000  0.0  0.0
B  1.0000  0.0000 -0.1667  0.0000 -0.6667  0.0000  0.0000 -0.1667  0.0  0.0
C -0.3334 -0.1667  0.0000  1.0000  0.3333 -0.1667 -0.1667 -0.5000  0.0  0.0
D -0.1667  0.0000  1.0000  0.0000 -0.6667  0.0000  0.0000 -0.1667  0.0  0.0
E  0.3333 -0.6667  0.3333 -0.6667  0.0000  0.5000  0.5000 -0.3334  0.0  0.0
F -0.1667  0.0000 -0.1667  0.0000  0.5000  0.0000  0.0000 -0.1667  0.0  0.0
G -0.1667  0.0000 -0.1667  0.0000  0.5000  0.0000  0.0000 -0.1667  0.0  0.0
H -0.5000 -0.1667 -0.5000 -0.1667 -0.3334 -0.1667 -0.1667  0.0000  1.0  1.0
I  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000  0.0 -1.0
J  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 -1.0  0.0

### Absolute value $\|I\|$

In [8]:
r_1_abs = r_1.astype(float).apply(lambda row: row.apply(lambda number: abs(number)))
r_1_abs

,A,B,C,D,E,F,G,H,I,J
A,0.000000,0.014286,0.004762,0.002381,0.004762,0.002381,0.002381,0.007143,0.000000,0.000000
B,0.014286,0.000000,0.002381,0.000000,0.009524,0.000000,0.000000,0.002381,0.000000,0.000000
C,0.004762,0.002381,0.000000,0.014286,0.004762,0.002381,0.002381,0.007143,0.000000,0.000000
D,0.002381,0.000000,0.014286,0.000000,0.009524,0.000000,0.000000,0.002381,0.000000,0.000000
E,0.004762,0.009524,0.004762,0.009524,0.000000,0.007143,0.007143,0.004762,0.000000,0.000000
F,0.002381,0.000000,0.002381,0.000000,0.007143,0.000000,0.000000,0.002381,0.000000,0.000000
G,0.002381,0.000000,0.002381,0.000000,0.007143,0.000000,0.000000,0.002381,0.000000,0.000000
H,0.007143,0.002381,0.007143,0.002381,0.004762,0.002381,0.002381,0.000000,0.014286,0.014286
I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014286,0.000000,0.014286
J,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014286,0.014286,0.000000

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 0}^{2}; R_{\beta^{+} = 0, \beta^{-} = 0}^{2}$

In [9]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=0,
    positive_beta=0,
    negative_beta=0,
    symmetric=True,
    layout="spring",
    label_margin=0.08,
    output_path=os.path.join("..", "..", "results", "voting-0-0-0-0.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\voting-0-0-0-0.jpg

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 0}^{2}; R_{\beta^{+} = 1; \beta^{-} = 0}^{2}$

In [26]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=0,
    positive_beta=1,
    negative_beta=0,
    symmetric=True,
    layout="kamada_kawai",
    label_margin=0.08,
    output_path=os.path.join("..", "..", "results", "voting-0-0-1-0.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\voting-0-0-1-0.jpg

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 0}^{2}; R_{\beta^{+} = 1; \beta^{-} = 0.1}^{2}$

In [25]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0.1,
    negative_alpha=0,
    positive_beta=1,
    negative_beta=0,
    symmetric=True,
    layout="kamada_kawai",
    label_margin=0.08,
    output_path=os.path.join("..", "..", "results", "voting-01-0-1-0.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\voting-01-0-1-0.jpg

## Histogram and Density Plots

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import itertools
import networkx as nx

In [13]:
from decimal import *

getcontext().prec = 28

r1_positive = r_1.copy(deep=True)
r1_positive[r1_positive < 0] = 0
r1_positive

r1_negative = r_1.copy(deep=True)
r1_negative[r1_negative > 0] = 0
r1_negative = r1_negative.abs()

s_plus = []
for column_name in r1_positive.columns:
    strength = Decimal(0)
    for value in r1_positive.loc[column_name]:
        strength = strength + Decimal(value)
    s_plus.append(round(float(strength), 4))
s_plus.sort()

s_minus = []
for column_name in r1_negative.columns:
    strength = Decimal(0)
    for value in r1_negative.loc[column_name]:
        strength = strength + Decimal(value)
    s_minus.append(round(float(strength), 4))
s_minus.sort()

s = []
for column_name in r_1.columns:
    strength = Decimal(0)
    for value in r_1.loc[column_name]:
        strength = strength + Decimal(value)
    s.append(round(float(strength), 4))
s.sort()

s_abs = []
for column_name in r_1.columns:
    strength = Decimal(0)
    for value in r_1.loc[column_name].abs():
        strength = strength + Decimal(value)
    s_abs.append(round(float(strength), 4))
s_abs.sort()

## Profiling

In [14]:
profile = pd.DataFrame(
    columns=["game", "parameter", "R = I+", "R = I-", "R = I", "R = |I|"]
)
game = "parliament"

### Stats

In [15]:
import numpy as np
from scipy.stats import skew, kurtosis

profile.loc[len(profile)] = [
    game,
    "max",
    np.max(s_plus),
    np.max(s_minus),
    np.max(s),
    np.max(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "Q3",
    np.percentile(s_plus, 75),
    np.percentile(s_minus, 75),
    np.percentile(s, 75),
    np.percentile(s_abs, 75),
]

profile.loc[len(profile)] = [
    game,
    "mean",
    np.mean(s_plus),
    np.mean(s_minus),
    np.mean(s),
    np.mean(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "median",
    np.median(s_plus),
    np.median(s_minus),
    np.median(s),
    np.median(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "Q1",
    np.percentile(s_plus, 25),
    np.percentile(s_minus, 25),
    np.percentile(s, 25),
    np.percentile(s_abs, 25),
]

profile.loc[len(profile)] = [
    game,
    "min",
    np.min(s_plus),
    np.min(s_minus),
    np.min(s),
    np.min(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "standard_deviation",
    np.std(s_plus),
    np.std(s_minus),
    np.std(s),
    np.std(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "skewness",
    0 if np.isnan(skew(list(s_plus))) else skew(list(s_plus)),
    0 if np.isnan(skew(list(s_minus))) else skew(list(s_minus)),
    0 if np.isnan(skew(list(s))) else skew(list(s)),
    0 if np.isnan(skew(list(s_abs))) else skew(list(s_abs)),
]

profile.loc[len(profile)] = [
    game,
    "kurtosis",
    0 if np.isnan(kurtosis(s_plus)) else kurtosis(s_plus),
    0 if np.isnan(kurtosis(s_minus)) else kurtosis(s_minus),
    0 if np.isnan(kurtosis(s)) else kurtosis(s),
    0 if np.isnan(kurtosis(s_abs)) else kurtosis(s_abs),
]

### Gini index

If we assign the strength of a player as the sum of all its connection in the relation matrix $r_{ij} \in N \times N$ with $n = |N|$ players

$$
s_{i} = \sum_{j \in N} r_{ij}
$$

We can compute the Gini index of a total resource $T$ defined as:

$$
T = \sum_{i \in N}{s_{i}}
$$

As described by Goswami (2021)[1] when $T_{1} = T$:

$$
SI(G) = 1 - \frac{2}{nT_{1}}\sum_{i \in N}{\left(n -i + \frac{1}{2}\right)s_{i}}
$$


[1] Goswami, S., Das, A. K., & Nandy, S. C. (2021). Sparsity of weighted networks: Measures and applications. Information Sciences, 577, 557–578. https://doi.org/10.1016/j.ins.2021.06.090

In [16]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import gini


profile.loc[len(profile)] = [
    game,
    "gini",
    gini(s_plus),
    gini(s_minus),
    gini(s),
    gini(s_abs),
]

### Degree centralization of the Graph

The degree centralization of a Graph was described by Freeman (1978)[2] as the ratio of the differences sum of degree of each node with the highest degree by the one that maximizes this value, the star graph:

$$
s_{i}^{*} = \max_{i} \left(s_{i}\right)
$$
$$
C_{D}(G) = \frac{\sum_{i \in N}{s_{i}^{*} - s_{i}}}{n^{2} - 3 n + 2}
$$

[2] Freeman, L. C. (1978). Centrality in social networks conceptual clarification. Social Networks, 1(3), 215–239. https://doi.org/10.1016/0378-8733(78)90021-7

In [17]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import degree_centralization


profile.loc[len(profile)] = [
    game,
    "degree_centralization",
    degree_centralization(s_plus),
    degree_centralization(s_minus),
    degree_centralization(s),
    degree_centralization(s_abs),
]

### Characteristic path length

Defined by Antoniou et al. (2008) [4] as:

$$
\tilde{w} = \frac{T}{|W|}
$$

where $W = [w_{ij}]$ is the set of edges weights in the weighted graph.

[4] Antoniou, I. E., & Tsompa, E. T. (2008). Statistical Analysis of Weighted Networks. Discrete Dynamics in Nature and Society, 2008, 1–16. https://doi.org/10.1155/2008/375452

In [18]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import characteristic_path_length


profile.loc[len(profile)] = [
    game,
    "characteristic_path_length",
    characteristic_path_length(s_plus),
    characteristic_path_length(s_minus),
    characteristic_path_length(s),
    characteristic_path_length(s_abs),
]

### Output results

In [19]:
import os

display(profile)

profiling_output = os.path.join(
    "..", "..", "data", "profiling", f"{game}.csv"
)

profile.to_csv(profiling_output, sep=";", index=False)

,game,parameter,R = I+,R = I-,R = I,R = |I|
0,parliament,max,0.028600,0.028600,0.0,0.057100
1,parliament,Q3,0.019000,0.019000,0.0,0.038100
2,parliament,mean,0.016180,0.016180,0.0,0.032390
3,parliament,median,0.014300,0.014300,0.0,0.028600
4,parliament,Q1,0.014300,0.014300,0.0,0.028600
5,parliament,min,0.007100,0.007100,0.0,0.014300
6,parliament,standard_deviation,0.006382,0.006382,0.0,0.012724
7,parliament,skewness,0.338350,0.338350,0.0,0.335942
8,parliament,kurtosis,-0.531749,-0.531749,0.0,-0.545377
9,parliament,gini,0.215080,0.215080,0.0,0.214356
10,parliament,degree_centralization,0.001725,0.001725,0.0,0.003432
11,parliament,characteristic_path_length,0.001798,0.001798,0.0,0.003599