### Ejemplo de coaliación del juego de los *Zapatos*

In [1]:
import os
import sys
import math
import pandas as pd


sys.path.append(os.path.join("..", "..", "."))

file_root_shapley = os.path.join(
    "..", "..", "data", "exact", "shapley_value_of_shoes.csv"
)
file_root_grabisch = os.path.join(
    "..", "..", "data", "exact", "grabisch_of_shoes.csv"
)
original = pd.read_csv(os.path.join(
    "..", "..", "data", "input", "shoes.csv"
), sep=";").set_index(
    "label",
    verify_integrity=True
)

shapley_only = pd.read_csv(
    file_root_shapley,
    sep=";",
    header=None,
    names=["value"]
)
shapley_only = shapley_only.set_index(
    original.index.values,
    verify_integrity=True
)
psi_1 = original.join(shapley_only)

r_1 = pd.read_csv(
    file_root_grabisch,
    sep=";",
    header=0
).set_index(
    original.index.values,
    verify_integrity=True
)
r_1.columns = original.index.values

### Truncated characteristic values

In [2]:
from graph.manipulation import normalize_psi, normalize_r


n = 4
psi_1_truncated = psi_1.copy()
psi_1_truncated["value"] = psi_1_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_1_truncated = r_1.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

psi_2 = normalize_psi(psi_1)
psi_2_truncated = psi_2.copy()
psi_2_truncated["value"] = psi_2_truncated["value"].astype(float).apply(lambda number: math.floor(number * 10 ** n) / 10 ** n)

r_2 = normalize_r(r_1)
r_2_truncated = r_2.astype(float).apply(lambda row: row.apply(lambda number: math.floor(number * 10 ** n) / 10 ** n))

#### Benefit Allocation Results

The Shapley values for this game are calculated in the file ./data/exact/shapley_value_of_shoes.csv. In the table below we represent these values:

In [3]:
psi_1_truncated

             player shoe  value
label
LS 1    Left Shoe 1    L    0.5
LS 2    Left Shoe 2    L    0.5
LS 3    Left Shoe 3    L    0.5
LS 4    Left Shoe 4    L    0.5
LS 5    Left Shoe 5    L    0.5
RS 1   Right Shoe 1    R    0.5
RS 2   Right Shoe 2    R    0.5
RS 3   Right Shoe 3    R    0.5
RS 4   Right Shoe 4    R    0.5
RS 5   Right Shoe 5    R    0.5

In [4]:
psi_2_truncated

             player shoe  value
label
LS 1    Left Shoe 1    L    1.0
LS 2    Left Shoe 2    L    1.0
LS 3    Left Shoe 3    L    1.0
LS 4    Left Shoe 4    L    1.0
LS 5    Left Shoe 5    L    1.0
RS 1   Right Shoe 1    R    1.0
RS 2   Right Shoe 2    R    1.0
RS 3   Right Shoe 3    R    1.0
RS 4   Right Shoe 4    R    1.0
RS 5   Right Shoe 5    R    1.0

The Grabisch values of all the pairs in the game can be found in the file ./data/exact/grabisch_of_shoes.csv. In the following table, we represent these values.

In [5]:
r_1_truncated

,LS 1,LS 2,LS 3,LS 4,LS 5,RS 1,RS 2,RS 3,RS 4,RS 5
LS 1,0.0000,-0.2580,-0.2580,-0.2580,-0.2580,0.4063,0.4063,0.4063,0.4063,0.4063
LS 2,-0.2580,0.0000,-0.2580,-0.2580,-0.2580,0.4063,0.4063,0.4063,0.4063,0.4063
LS 3,-0.2580,-0.2580,0.0000,-0.2580,-0.2580,0.4063,0.4063,0.4063,0.4063,0.4063
LS 4,-0.2580,-0.2580,-0.2580,0.0000,-0.2580,0.4063,0.4063,0.4063,0.4063,0.4063
LS 5,-0.2580,-0.2580,-0.2580,-0.2580,0.0000,0.4063,0.4063,0.4063,0.4063,0.4063
RS 1,0.4063,0.4063,0.4063,0.4063,0.4063,0.0000,-0.2580,-0.2580,-0.2580,-0.2580
RS 2,0.4063,0.4063,0.4063,0.4063,0.4063,-0.2580,0.0000,-0.2580,-0.2580,-0.2580
RS 3,0.4063,0.4063,0.4063,0.4063,0.4063,-0.2580,-0.2580,0.0000,-0.2580,-0.2580
RS 4,0.4063,0.4063,0.4063,0.4063,0.4063,-0.2580,-0.2580,-0.2580,0.0000,-0.2580
RS 5,0.4063,0.4063,0.4063,0.4063,0.4063,-0.2580,-0.2580,-0.2580,-0.2580,0.0000

In [6]:
r_2_truncated

,LS 1,LS 2,LS 3,LS 4,LS 5,RS 1,RS 2,RS 3,RS 4,RS 5
LS 1,0.0000,-0.6348,-0.6348,-0.6348,-0.6348,1.0000,1.0000,1.0000,1.0000,1.0000
LS 2,-0.6348,0.0000,-0.6348,-0.6348,-0.6348,1.0000,1.0000,1.0000,1.0000,1.0000
LS 3,-0.6348,-0.6348,0.0000,-0.6348,-0.6348,1.0000,1.0000,1.0000,1.0000,1.0000
LS 4,-0.6348,-0.6348,-0.6348,0.0000,-0.6348,1.0000,1.0000,1.0000,1.0000,1.0000
LS 5,-0.6348,-0.6348,-0.6348,-0.6348,0.0000,1.0000,1.0000,1.0000,1.0000,1.0000
RS 1,1.0000,1.0000,1.0000,1.0000,1.0000,0.0000,-0.6348,-0.6348,-0.6348,-0.6348
RS 2,1.0000,1.0000,1.0000,1.0000,1.0000,-0.6348,0.0000,-0.6348,-0.6348,-0.6348
RS 3,1.0000,1.0000,1.0000,1.0000,1.0000,-0.6348,-0.6348,0.0000,-0.6348,-0.6348
RS 4,1.0000,1.0000,1.0000,1.0000,1.0000,-0.6348,-0.6348,-0.6348,0.0000,-0.6348
RS 5,1.0000,1.0000,1.0000,1.0000,1.0000,-0.6348,-0.6348,-0.6348,-0.6348,0.0000

### Absolute value $\|I\|$

In [7]:
r_1_abs = r_1.astype(float).apply(lambda row: row.apply(lambda number: abs(number)))
r_1_abs

,LS 1,LS 2,LS 3,LS 4,LS 5,RS 1,RS 2,RS 3,RS 4,RS 5
LS 1,0.000000,0.257937,0.257937,0.257937,0.257937,0.406349,0.406349,0.406349,0.406349,0.406349
LS 2,0.257937,0.000000,0.257937,0.257937,0.257937,0.406349,0.406349,0.406349,0.406349,0.406349
LS 3,0.257937,0.257937,0.000000,0.257937,0.257937,0.406349,0.406349,0.406349,0.406349,0.406349
LS 4,0.257937,0.257937,0.257937,0.000000,0.257937,0.406349,0.406349,0.406349,0.406349,0.406349
LS 5,0.257937,0.257937,0.257937,0.257937,0.000000,0.406349,0.406349,0.406349,0.406349,0.406349
RS 1,0.406349,0.406349,0.406349,0.406349,0.406349,0.000000,0.257937,0.257937,0.257937,0.257937
RS 2,0.406349,0.406349,0.406349,0.406349,0.406349,0.257937,0.000000,0.257937,0.257937,0.257937
RS 3,0.406349,0.406349,0.406349,0.406349,0.406349,0.257937,0.257937,0.000000,0.257937,0.257937
RS 4,0.406349,0.406349,0.406349,0.406349,0.406349,0.257937,0.257937,0.257937,0.000000,0.257937
RS 5,0.406349,0.406349,0.406349,0.406349,0.406349,0.257937,0.257937,0.257937,0.257937,0.000000

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 1}^{2}; R_{\beta^{+} = 1; \beta^{-} = 0}^{2}$

In [8]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=1,
    positive_beta=1,
    negative_beta=0,
    symmetric=True,
    layout="twopi",
    negative_color="black",
    output_path=os.path.join("..", "..", "results", "shoes-0-1-1-0.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\shoes-0-1-1-0.jpg

####  $\Psi_{\alpha^{+} = 0, \alpha^{-} = 1}^{2}; R_{\beta^{+} = 0; \beta^{-} = 1}^{2}$

In [9]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.visualization import draw


node_pos = {
    "LS 5": [1, 5],
    "LS 4": [1, 4],
    "LS 3": [1, 3],
    "LS 2": [1, 2],
    "LS 1": [1, 1],
    "RS 5": [5, 5],
    "RS 4": [5, 4],
    "RS 3": [5, 3],
    "RS 2": [5, 2],
    "RS 1": [5, 1],
}

draw(
    psi=psi_2,
    r=r_2,
    positive_alpha=0,
    negative_alpha=1,
    positive_beta=0,
    negative_beta=1,
    symmetric=True,
    # layout="circular",
    node_pos=node_pos,
    output_path=os.path.join("..", "..", "results", "shoes-0-1-0-1.jpg")
)

..\..\.\graph\visualization.py:204: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

Saving the graph to ..\..\results\shoes-0-1-0-1.jpg

## Histogram and Density Plots

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import itertools
import networkx as nx

In [12]:
r1_positive = r_1.copy(deep=True)
r1_positive[r1_positive < 0] = 0
r1_positive

r1_negative = r_1.copy(deep=True)
r1_negative[r1_negative > 0] = 0
r1_negative = r1_negative.abs()

s_plus = []
for column_name in r1_positive.columns:
    strength = r1_positive.loc[column_name].sum()
    s_plus.append(math.floor(strength * 10 ** n) / 10 ** n)
s_plus.sort()

s_minus = []
for column_name in r1_negative.columns:
    strength = r1_negative.loc[column_name].sum()
    s_minus.append(math.floor(strength * 10 ** n) / 10 ** n)
s_minus.sort()

s = []
for column_name in r_1.columns:
    strength = r_1.loc[column_name].sum()
    s.append(math.floor(strength * 10 ** n) / 10 ** n)
s.sort()

s_abs = []
for column_name in r_1.columns:
    strength = r_1.abs().loc[column_name].sum()
    s_abs.append(math.floor(strength * 10 ** n) / 10 ** n)
s_abs.sort()

## Profiling

In [13]:
profile = pd.DataFrame(
    columns=["game", "parameter", "R = I+", "R = I-", "R = I", "R = |I|"]
)
game = "shoes"

### Stats

In [14]:
import numpy as np
from scipy.stats import skew, kurtosis

profile.loc[len(profile)] = [
    game,
    "max",
    np.max(s_plus),
    np.max(s_minus),
    np.max(s),
    np.max(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "Q3",
    np.percentile(s_plus, 75),
    np.percentile(s_minus, 75),
    np.percentile(s, 75),
    np.percentile(s_abs, 75),
]

profile.loc[len(profile)] = [
    game,
    "mean",
    np.mean(s_plus),
    np.mean(s_minus),
    np.mean(s),
    np.mean(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "median",
    np.median(s_plus),
    np.median(s_minus),
    np.median(s),
    np.median(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "Q1",
    np.percentile(s_plus, 25),
    np.percentile(s_minus, 25),
    np.percentile(s, 25),
    np.percentile(s_abs, 25),
]

profile.loc[len(profile)] = [
    game,
    "min",
    np.min(s_plus),
    np.min(s_minus),
    np.min(s),
    np.min(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "standard_deviation",
    np.std(s_plus),
    np.std(s_minus),
    np.std(s),
    np.std(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "skewness",
    0 if np.isnan(skew(s_plus)) else skew(s_plus),
    0 if np.isnan(skew(s_minus)) else skew(s_minus),
    0 if np.isnan(skew(s)) else skew(s),
    0 if np.isnan(skew(s_abs)) else skew(s_abs),
]

profile.loc[len(profile)] = [
    game,
    "kurtosis",
    0 if np.isnan(kurtosis(s_plus)) else kurtosis(s_plus),
    0 if np.isnan(kurtosis(s_minus)) else kurtosis(s_minus),
    0 if np.isnan(kurtosis(s)) else kurtosis(s),
    0 if np.isnan(kurtosis(s_abs)) else kurtosis(s_abs),
]

C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:70: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(skew(s_plus)) else skew(s_plus),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:71: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(skew(s_minus)) else skew(s_minus),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:72: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(skew(s)) else skew(s),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:73: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(skew(s_abs)) else skew(s_abs),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(kurtosis(s_plus)) else kurtosis(s_plus),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:80: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(kurtosis(s_minus)) else kurtosis(s_minus),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:81: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(kurtosis(s)) else kurtosis(s),
C:\Users\secci\AppData\Local\Temp\ipykernel_14812\3198586119.py:82: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  0 if np.isnan(kurtosis(s_abs)) else kurtosis(s_abs),

### Gini index

If we assign the strength of a player as the sum of all its connection in the relation matrix $r_{ij} \in N \times N$ with $n = |N|$ players

$$
s_{i} = \sum_{j \in N} r_{ij}
$$

We can compute the Gini index of a total resource $T$ defined as:

$$
T = \sum_{i \in N}{s_{i}}
$$

As described by Goswami (2021)[1] when $T_{1} = T$:

$$
SI(G) = 1 - \frac{2}{nT_{1}}\sum_{i \in N}{\left(n -i + \frac{1}{2}\right)s_{i}}
$$


[1] Goswami, S., Das, A. K., & Nandy, S. C. (2021). Sparsity of weighted networks: Measures and applications. Information Sciences, 577, 557–578. https://doi.org/10.1016/j.ins.2021.06.090

In [15]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import gini


profile.loc[len(profile)] = [
    game,
    "gini",
    gini(s_plus),
    gini(s_minus),
    gini(s),
    gini(s_abs),
]

### Degree centralization of the Graph

The degree centralization of a Graph was described by Freeman (1978)[2] as the ratio of the differences sum of degree of each node with the highest degree by the one that maximizes this value, the star graph:

$$
s_{i}^{*} = \max_{i} \left(s_{i}\right)
$$
$$
C_{D}(G) = \frac{\sum_{i \in N}{s_{i}^{*} - s_{i}}}{n^{2} - 3 n + 2}
$$

[2] Freeman, L. C. (1978). Centrality in social networks conceptual clarification. Social Networks, 1(3), 215–239. https://doi.org/10.1016/0378-8733(78)90021-7

In [16]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import degree_centralization


profile.loc[len(profile)] = [
    game,
    "degree_centralization",
    degree_centralization(s_plus),
    degree_centralization(s_minus),
    degree_centralization(s),
    degree_centralization(s_abs),
]

### Characteristic path length

Defined by Antoniou et al. (2008) [4] as:

$$
\tilde{w} = \frac{T}{|W|}
$$

where $W = [w_{ij}]$ is the set of edges weights in the weighted graph.

[4] Antoniou, I. E., & Tsompa, E. T. (2008). Statistical Analysis of Weighted Networks. Discrete Dynamics in Nature and Society, 2008, 1–16. https://doi.org/10.1155/2008/375452

In [17]:
import os
import sys
sys.path.append(os.path.join("..", "..", "."))

from graph.parameters import characteristic_path_length


profile.loc[len(profile)] = [
    game,
    "characteristic_path_length",
    characteristic_path_length(s_plus),
    characteristic_path_length(s_minus),
    characteristic_path_length(s),
    characteristic_path_length(s_abs),
]

### Output results

In [18]:
import os

display(profile)

profiling_output = os.path.join(
    "..", "..", "data", "profiling", f"{game}.csv"
)

profile.to_csv(profiling_output, sep=";", index=False)

,game,parameter,R = I+,R = I-,R = I,R = |I|
0,shoes,max,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
1,shoes,Q3,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
2,shoes,mean,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
3,shoes,median,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
4,shoes,Q1,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
5,shoes,min,2.031700e+00,1.031700e+00,9.999000e-01,3.063400e+00
6,shoes,standard_deviation,0.000000e+00,2.220446e-16,0.000000e+00,4.440892e-16
7,shoes,skewness,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
8,shoes,kurtosis,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
9,shoes,gini,2.622961e-16,1.291332e-16,4.441336e-17,2.029526e-16
10,shoes,degree_centralization,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
11,shoes,characteristic_path_length,2.257444e-01,1.146333e-01,1.111000e-01,3.403778e-01